namespace OraclaMajorAssignmentY3S2
{
    partial class InputForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(InputForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.InputTabControll = new Guna.UI2.WinForms.Guna2TabControl();
            this.StudentTab = new System.Windows.Forms.TabPage();
            this.guna2PictureBox1 = new Guna.UI2.WinForms.Guna2PictureBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.dtpDob = new Guna.UI2.WinForms.Guna2DateTimePicker();
            this.tbLastname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbFirstname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbContact = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cbGender = new Guna.UI2.WinForms.Guna2ComboBox();
            this.btnCancelStudentTab = new Guna.UI2.WinForms.Guna2Button();
            this.btnTakePhoto = new Guna.UI2.WinForms.Guna2Button();
            this.btnFromfile = new Guna.UI2.WinForms.Guna2Button();
            this.btnNext = new Guna.UI2.WinForms.Guna2Button();
            this.familyTab = new System.Windows.Forms.TabPage();
            this.label3 = new System.Windows.Forms.Label();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.tbFatheroccupation = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbFathername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbMotheroccupation = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbParentcontact = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbMothername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnCancelFamilyTab = new Guna.UI2.WinForms.Guna2Button();
            this.btnInsert = new Guna.UI2.WinForms.Guna2Button();
            this.btnBack = new Guna.UI2.WinForms.Guna2Button();
            this.guna2Panel1 = new Guna.UI2.WinForms.Guna2Panel();
            this.guna2DragControl1 = new Guna.UI2.WinForms.Guna2DragControl(this.components);
            this.InputTabControll.SuspendLayout();
            this.StudentTab.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.guna2PictureBox1)).BeginInit();
            this.tableLayoutPanel1.SuspendLayout();
            this.familyTab.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // InputTabControll
            // 
            this.InputTabControll.Alignment = System.Windows.Forms.TabAlignment.Left;
            this.InputTabControll.Controls.Add(this.StudentTab);
            this.InputTabControll.Controls.Add(this.familyTab);
            this.InputTabControll.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.InputTabControll.ItemSize = new System.Drawing.Size(180, 40);
            this.InputTabControll.Location = new System.Drawing.Point(0, 23);
            this.InputTabControll.Name = "InputTabControll";
            this.InputTabControll.SelectedIndex = 0;
            this.InputTabControll.Size = new System.Drawing.Size(721, 506);
            this.InputTabControll.TabButtonHoverState.BorderColor = System.Drawing.Color.Empty;
            this.InputTabControll.TabButtonHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(52)))), ((int)(((byte)(70)))));
            this.InputTabControll.TabButtonHoverState.Font = new System.Drawing.Font("Segoe UI Semibold", 10F);
            this.InputTabControll.TabButtonHoverState.ForeColor = System.Drawing.Color.White;
            this.InputTabControll.TabButtonHoverState.InnerColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(52)))), ((int)(((byte)(70)))));
            this.InputTabControll.TabButtonIdleState.BorderColor = System.Drawing.Color.Empty;
            this.InputTabControll.TabButtonIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(42)))), ((int)(((byte)(57)))));
            this.InputTabControll.TabButtonIdleState.Font = new System.Drawing.Font("Segoe UI Semibold", 10F);
            this.InputTabControll.TabButtonIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(156)))), ((int)(((byte)(160)))), ((int)(((byte)(167)))));
            this.InputTabControll.TabButtonIdleState.InnerColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(42)))), ((int)(((byte)(57)))));
            this.InputTabControll.TabButtonSelectedState.BorderColor = System.Drawing.Color.Empty;
            this.InputTabControll.TabButtonSelectedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(37)))), ((int)(((byte)(49)))));
            this.InputTabControll.TabButtonSelectedState.Font = new System.Drawing.Font("Segoe UI Semibold", 10F);
            this.InputTabControll.TabButtonSelectedState.ForeColor = System.Drawing.Color.White;
            this.InputTabControll.TabButtonSelectedState.InnerColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(132)))), ((int)(((byte)(255)))));
            this.InputTabControll.TabButtonSize = new System.Drawing.Size(180, 40);
            this.InputTabControll.TabIndex = 0;
            this.InputTabControll.TabMenuBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(42)))), ((int)(((byte)(57)))));
            this.InputTabControll.TabMenuVisible = false;
            // 
            // StudentTab
            // 
            this.StudentTab.Controls.Add(this.guna2PictureBox1);
            this.StudentTab.Controls.Add(this.label2);
            this.StudentTab.Controls.Add(this.label1);
            this.StudentTab.Controls.Add(this.tableLayoutPanel1);
            this.StudentTab.Controls.Add(this.btnCancelStudentTab);
            this.StudentTab.Controls.Add(this.btnTakePhoto);
            this.StudentTab.Controls.Add(this.btnFromfile);
            this.StudentTab.Controls.Add(this.btnNext);
            this.StudentTab.Location = new System.Drawing.Point(5, 4);
            this.StudentTab.Name = "StudentTab";
            this.StudentTab.Padding = new System.Windows.Forms.Padding(3);
            this.StudentTab.Size = new System.Drawing.Size(712, 498);
            this.StudentTab.TabIndex = 1;
            this.StudentTab.Text = "Student";
            this.StudentTab.UseVisualStyleBackColor = true;
            // 
            // guna2PictureBox1
            // 
            this.guna2PictureBox1.ImageRotate = 0F;
            this.guna2PictureBox1.Location = new System.Drawing.Point(517, 116);
            this.guna2PictureBox1.Name = "guna2PictureBox1";
            this.guna2PictureBox1.Size = new System.Drawing.Size(185, 214);
            this.guna2PictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.guna2PictureBox1.TabIndex = 12;
            this.guna2PictureBox1.TabStop = false;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Century Gothic", 20F);
            this.label2.ForeColor = System.Drawing.SystemColors.Desktop;
            this.label2.Location = new System.Drawing.Point(510, 70);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(202, 33);
            this.label2.TabIndex = 11;
            this.label2.Text = "Student Photo";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Century Gothic", 20F);
            this.label1.ForeColor = System.Drawing.SystemColors.Desktop;
            this.label1.Location = new System.Drawing.Point(7, 16);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(195, 33);
            this.label1.TabIndex = 11;
            this.label1.Text = "Add Student :";
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Controls.Add(this.dtpDob, 1, 2);
            this.tableLayoutPanel1.Controls.Add(this.tbLastname, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.tbFirstname, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.tbContact, 1, 1);
            this.tableLayoutPanel1.Controls.Add(this.tbEmail, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.cbGender, 0, 1);
            this.tableLayoutPanel1.Location = new System.Drawing.Point(7, 70);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 3;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(485, 377);
            this.tableLayoutPanel1.TabIndex = 9;
            // 
            // dtpDob
            // 
            this.dtpDob.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.dtpDob.Animated = true;
            this.dtpDob.BorderRadius = 10;
            this.dtpDob.Checked = true;
            this.dtpDob.FillColor = System.Drawing.Color.White;
            this.dtpDob.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dtpDob.Format = System.Windows.Forms.DateTimePickerFormat.Long;
            this.dtpDob.Location = new System.Drawing.Point(259, 295);
            this.dtpDob.MaxDate = new System.DateTime(9998, 12, 31, 0, 0, 0, 0);
            this.dtpDob.MinDate = new System.DateTime(1753, 1, 1, 0, 0, 0, 0);
            this.dtpDob.Name = "dtpDob";
            this.dtpDob.Size = new System.Drawing.Size(208, 37);
            this.dtpDob.TabIndex = 12;
            this.dtpDob.Value = new System.DateTime(2024, 6, 19, 16, 33, 26, 644);
            // 
            // tbLastname
            // 
            this.tbLastname.AcceptsReturn = false;
            this.tbLastname.AcceptsTab = false;
            this.tbLastname.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbLastname.AnimationSpeed = 200;
            this.tbLastname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbLastname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbLastname.BackColor = System.Drawing.Color.Transparent;
            this.tbLastname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbLastname.BackgroundImage")));
            this.tbLastname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbLastname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbLastname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbLastname.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbLastname.BorderRadius = 10;
            this.tbLastname.BorderThickness = 2;
            this.tbLastname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbLastname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbLastname.DefaultText = "";
            this.tbLastname.FillColor = System.Drawing.Color.White;
            this.tbLastname.HideSelection = true;
            this.tbLastname.IconLeft = null;
            this.tbLastname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastname.IconPadding = 10;
            this.tbLastname.IconRight = null;
            this.tbLastname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastname.Lines = new string[0];
            this.tbLastname.Location = new System.Drawing.Point(259, 44);
            this.tbLastname.MaxLength = 32767;
            this.tbLastname.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbLastname.Modified = false;
            this.tbLastname.Multiline = false;
            this.tbLastname.Name = "tbLastname";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastname.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbLastname.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastname.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastname.OnIdleState = stateProperties4;
            this.tbLastname.Padding = new System.Windows.Forms.Padding(3);
            this.tbLastname.PasswordChar = '\0';
            this.tbLastname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbLastname.PlaceholderText = "Last Name";
            this.tbLastname.ReadOnly = false;
            this.tbLastname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbLastname.SelectedText = "";
            this.tbLastname.SelectionLength = 0;
            this.tbLastname.SelectionStart = 0;
            this.tbLastname.ShortcutsEnabled = true;
            this.tbLastname.Size = new System.Drawing.Size(208, 37);
            this.tbLastname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbLastname.TabIndex = 3;
            this.tbLastname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbLastname.TextMarginBottom = 0;
            this.tbLastname.TextMarginLeft = 3;
            this.tbLastname.TextMarginTop = 0;
            this.tbLastname.TextPlaceholder = "Last Name";
            this.tbLastname.UseSystemPasswordChar = false;
            this.tbLastname.WordWrap = true;
            // 
            // tbFirstname
            // 
            this.tbFirstname.AcceptsReturn = false;
            this.tbFirstname.AcceptsTab = false;
            this.tbFirstname.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbFirstname.AnimationSpeed = 200;
            this.tbFirstname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbFirstname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbFirstname.BackColor = System.Drawing.Color.Transparent;
            this.tbFirstname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbFirstname.BackgroundImage")));
            this.tbFirstname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbFirstname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbFirstname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbFirstname.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbFirstname.BorderRadius = 10;
            this.tbFirstname.BorderThickness = 2;
            this.tbFirstname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbFirstname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbFirstname.DefaultText = "";
            this.tbFirstname.FillColor = System.Drawing.Color.White;
            this.tbFirstname.HideSelection = true;
            this.tbFirstname.IconLeft = null;
            this.tbFirstname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstname.IconPadding = 10;
            this.tbFirstname.IconRight = null;
            this.tbFirstname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstname.Lines = new string[0];
            this.tbFirstname.Location = new System.Drawing.Point(17, 44);
            this.tbFirstname.MaxLength = 32767;
            this.tbFirstname.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbFirstname.Modified = false;
            this.tbFirstname.Multiline = false;
            this.tbFirstname.Name = "tbFirstname";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstname.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbFirstname.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstname.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstname.OnIdleState = stateProperties8;
            this.tbFirstname.Padding = new System.Windows.Forms.Padding(3);
            this.tbFirstname.PasswordChar = '\0';
            this.tbFirstname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbFirstname.PlaceholderText = "First Name";
            this.tbFirstname.ReadOnly = false;
            this.tbFirstname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbFirstname.SelectedText = "";
            this.tbFirstname.SelectionLength = 0;
            this.tbFirstname.SelectionStart = 0;
            this.tbFirstname.ShortcutsEnabled = true;
            this.tbFirstname.Size = new System.Drawing.Size(208, 37);
            this.tbFirstname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbFirstname.TabIndex = 3;
            this.tbFirstname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbFirstname.TextMarginBottom = 0;
            this.tbFirstname.TextMarginLeft = 3;
            this.tbFirstname.TextMarginTop = 0;
            this.tbFirstname.TextPlaceholder = "First Name";
            this.tbFirstname.UseSystemPasswordChar = false;
            this.tbFirstname.WordWrap = true;
            // 
            // tbContact
            // 
            this.tbContact.AcceptsReturn = false;
            this.tbContact.AcceptsTab = false;
            this.tbContact.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbContact.AnimationSpeed = 200;
            this.tbContact.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbContact.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbContact.BackColor = System.Drawing.Color.Transparent;
            this.tbContact.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbContact.BackgroundImage")));
            this.tbContact.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbContact.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbContact.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbContact.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbContact.BorderRadius = 10;
            this.tbContact.BorderThickness = 2;
            this.tbContact.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbContact.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbContact.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbContact.DefaultText = "";
            this.tbContact.FillColor = System.Drawing.Color.White;
            this.tbContact.HideSelection = true;
            this.tbContact.IconLeft = null;
            this.tbContact.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbContact.IconPadding = 10;
            this.tbContact.IconRight = null;
            this.tbContact.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbContact.Lines = new string[0];
            this.tbContact.Location = new System.Drawing.Point(259, 169);
            this.tbContact.MaxLength = 32767;
            this.tbContact.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbContact.Modified = false;
            this.tbContact.Multiline = false;
            this.tbContact.Name = "tbContact";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbContact.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbContact.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbContact.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbContact.OnIdleState = stateProperties12;
            this.tbContact.Padding = new System.Windows.Forms.Padding(3);
            this.tbContact.PasswordChar = '\0';
            this.tbContact.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbContact.PlaceholderText = "Contact Number";
            this.tbContact.ReadOnly = false;
            this.tbContact.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbContact.SelectedText = "";
            this.tbContact.SelectionLength = 0;
            this.tbContact.SelectionStart = 0;
            this.tbContact.ShortcutsEnabled = true;
            this.tbContact.Size = new System.Drawing.Size(208, 37);
            this.tbContact.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbContact.TabIndex = 3;
            this.tbContact.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbContact.TextMarginBottom = 0;
            this.tbContact.TextMarginLeft = 3;
            this.tbContact.TextMarginTop = 0;
            this.tbContact.TextPlaceholder = "Contact Number";
            this.tbContact.UseSystemPasswordChar = false;
            this.tbContact.WordWrap = true;
            // 
            // tbEmail
            // 
            this.tbEmail.AcceptsReturn = false;
            this.tbEmail.AcceptsTab = false;
            this.tbEmail.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbEmail.AnimationSpeed = 200;
            this.tbEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbEmail.BackColor = System.Drawing.Color.Transparent;
            this.tbEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbEmail.BackgroundImage")));
            this.tbEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbEmail.BorderRadius = 10;
            this.tbEmail.BorderThickness = 2;
            this.tbEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbEmail.DefaultText = "";
            this.tbEmail.FillColor = System.Drawing.Color.White;
            this.tbEmail.HideSelection = true;
            this.tbEmail.IconLeft = null;
            this.tbEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.IconPadding = 10;
            this.tbEmail.IconRight = null;
            this.tbEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.Lines = new string[0];
            this.tbEmail.Location = new System.Drawing.Point(17, 295);
            this.tbEmail.MaxLength = 32767;
            this.tbEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbEmail.Modified = false;
            this.tbEmail.Multiline = false;
            this.tbEmail.Name = "tbEmail";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbEmail.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnIdleState = stateProperties16;
            this.tbEmail.Padding = new System.Windows.Forms.Padding(3);
            this.tbEmail.PasswordChar = '\0';
            this.tbEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbEmail.PlaceholderText = "Email";
            this.tbEmail.ReadOnly = false;
            this.tbEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbEmail.SelectedText = "";
            this.tbEmail.SelectionLength = 0;
            this.tbEmail.SelectionStart = 0;
            this.tbEmail.ShortcutsEnabled = true;
            this.tbEmail.Size = new System.Drawing.Size(208, 37);
            this.tbEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbEmail.TabIndex = 3;
            this.tbEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbEmail.TextMarginBottom = 0;
            this.tbEmail.TextMarginLeft = 3;
            this.tbEmail.TextMarginTop = 0;
            this.tbEmail.TextPlaceholder = "Email";
            this.tbEmail.UseSystemPasswordChar = false;
            this.tbEmail.WordWrap = true;
            // 
            // cbGender
            // 
            this.cbGender.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.cbGender.BackColor = System.Drawing.Color.Transparent;
            this.cbGender.BorderRadius = 10;
            this.cbGender.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbGender.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbGender.FocusedColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.cbGender.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.cbGender.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cbGender.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(88)))), ((int)(((byte)(112)))));
            this.cbGender.ItemHeight = 30;
            this.cbGender.Location = new System.Drawing.Point(17, 169);
            this.cbGender.Name = "cbGender";
            this.cbGender.Size = new System.Drawing.Size(208, 36);
            this.cbGender.TabIndex = 4;
            this.cbGender.SelectedIndexChanged += new System.EventHandler(this.cbGender_SelectedIndexChanged);
            // 
            // btnCancelStudentTab
            // 
            this.btnCancelStudentTab.Animated = true;
            this.btnCancelStudentTab.AnimatedGIF = true;
            this.btnCancelStudentTab.BackColor = System.Drawing.Color.Transparent;
            this.btnCancelStudentTab.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btnCancelStudentTab.BorderRadius = 12;
            this.btnCancelStudentTab.BorderThickness = 1;
            this.btnCancelStudentTab.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnCancelStudentTab.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnCancelStudentTab.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnCancelStudentTab.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnCancelStudentTab.FillColor = System.Drawing.Color.Transparent;
            this.btnCancelStudentTab.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnCancelStudentTab.ForeColor = System.Drawing.Color.Black;
            this.btnCancelStudentTab.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(190)))), ((int)(((byte)(51)))), ((int)(((byte)(0)))));
            this.btnCancelStudentTab.HoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(190)))), ((int)(((byte)(51)))), ((int)(((byte)(0)))));
            this.btnCancelStudentTab.HoverState.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.cancel__1_;
            this.btnCancelStudentTab.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.cancel;
            this.btnCancelStudentTab.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.btnCancelStudentTab.Location = new System.Drawing.Point(3, 453);
            this.btnCancelStudentTab.Name = "btnCancelStudentTab";
            this.btnCancelStudentTab.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(190)))), ((int)(((byte)(51)))), ((int)(((byte)(0)))));
            this.btnCancelStudentTab.Size = new System.Drawing.Size(110, 39);
            this.btnCancelStudentTab.TabIndex = 8;
            this.btnCancelStudentTab.Text = "Cancel";
            this.btnCancelStudentTab.UseTransparentBackground = true;
            this.btnCancelStudentTab.Click += new System.EventHandler(this.btnCancelStudentTab_Click);
            // 
            // btnTakePhoto
            // 
            this.btnTakePhoto.Animated = true;
            this.btnTakePhoto.AnimatedGIF = true;
            this.btnTakePhoto.BackColor = System.Drawing.Color.Transparent;
            this.btnTakePhoto.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btnTakePhoto.BorderRadius = 12;
            this.btnTakePhoto.BorderThickness = 1;
            this.btnTakePhoto.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnTakePhoto.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnTakePhoto.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnTakePhoto.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnTakePhoto.FillColor = System.Drawing.Color.Transparent;
            this.btnTakePhoto.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnTakePhoto.ForeColor = System.Drawing.Color.Black;
            this.btnTakePhoto.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(138)))), ((int)(((byte)(255)))));
            this.btnTakePhoto.HoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(96)))), ((int)(((byte)(164)))));
            this.btnTakePhoto.HoverState.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.camera__1_;
            this.btnTakePhoto.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.camera;
            this.btnTakePhoto.ImageAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.btnTakePhoto.Location = new System.Drawing.Point(614, 336);
            this.btnTakePhoto.Name = "btnTakePhoto";
            this.btnTakePhoto.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(239)))), ((int)(((byte)(209)))));
            this.btnTakePhoto.Size = new System.Drawing.Size(40, 39);
            this.btnTakePhoto.TabIndex = 4;
            this.btnTakePhoto.UseTransparentBackground = true;
            this.btnTakePhoto.Click += new System.EventHandler(this.btnTakePhoto_Click);
            // 
            // btnFromfile
            // 
            this.btnFromfile.Animated = true;
            this.btnFromfile.AnimatedGIF = true;
            this.btnFromfile.BackColor = System.Drawing.Color.Transparent;
            this.btnFromfile.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btnFromfile.BorderRadius = 12;
            this.btnFromfile.BorderThickness = 1;
            this.btnFromfile.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnFromfile.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnFromfile.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnFromfile.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnFromfile.FillColor = System.Drawing.Color.Transparent;
            this.btnFromfile.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnFromfile.ForeColor = System.Drawing.Color.Black;
            this.btnFromfile.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(138)))), ((int)(((byte)(255)))));
            this.btnFromfile.HoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(96)))), ((int)(((byte)(164)))));
            this.btnFromfile.HoverState.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.file;
            this.btnFromfile.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.file__1_;
            this.btnFromfile.ImageAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.btnFromfile.Location = new System.Drawing.Point(568, 336);
            this.btnFromfile.Name = "btnFromfile";
            this.btnFromfile.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(239)))), ((int)(((byte)(209)))));
            this.btnFromfile.Size = new System.Drawing.Size(40, 39);
            this.btnFromfile.TabIndex = 4;
            this.btnFromfile.UseTransparentBackground = true;
            this.btnFromfile.Click += new System.EventHandler(this.btnFromfile_Click);
            // 
            // btnNext
            // 
            this.btnNext.Animated = true;
            this.btnNext.AnimatedGIF = true;
            this.btnNext.BackColor = System.Drawing.Color.Transparent;
            this.btnNext.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btnNext.BorderRadius = 12;
            this.btnNext.BorderThickness = 1;
            this.btnNext.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnNext.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnNext.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnNext.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnNext.FillColor = System.Drawing.Color.Transparent;
            this.btnNext.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnNext.ForeColor = System.Drawing.Color.Black;
            this.btnNext.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(138)))), ((int)(((byte)(255)))));
            this.btnNext.HoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(96)))), ((int)(((byte)(164)))));
            this.btnNext.HoverState.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.next_button;
            this.btnNext.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.next_button__2_;
            this.btnNext.ImageAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.btnNext.Location = new System.Drawing.Point(662, 4);
            this.btnNext.Name = "btnNext";
            this.btnNext.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(239)))), ((int)(((byte)(209)))));
            this.btnNext.Size = new System.Drawing.Size(40, 39);
            this.btnNext.TabIndex = 4;
            this.btnNext.UseTransparentBackground = true;
            this.btnNext.Click += new System.EventHandler(this.btnNext_Click);
            // 
            // familyTab
            // 
            this.familyTab.Controls.Add(this.label3);
            this.familyTab.Controls.Add(this.tableLayoutPanel2);
            this.familyTab.Controls.Add(this.btnCancelFamilyTab);
            this.familyTab.Controls.Add(this.btnInsert);
            this.familyTab.Controls.Add(this.btnBack);
            this.familyTab.Location = new System.Drawing.Point(184, 4);
            this.familyTab.Name = "familyTab";
            this.familyTab.Padding = new System.Windows.Forms.Padding(3);
            this.familyTab.Size = new System.Drawing.Size(533, 498);
            this.familyTab.TabIndex = 2;
            this.familyTab.Text = "Family BG";
            this.familyTab.UseVisualStyleBackColor = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Century Gothic", 20F);
            this.label3.ForeColor = System.Drawing.SystemColors.Desktop;
            this.label3.Location = new System.Drawing.Point(174, 67);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(375, 33);
            this.label3.TabIndex = 12;
            this.label3.Text = "Student Family Background";
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.Controls.Add(this.tbFatheroccupation, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.tbFathername, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.tbMotheroccupation, 1, 1);
            this.tableLayoutPanel2.Controls.Add(this.tbParentcontact, 0, 2);
            this.tableLayoutPanel2.Controls.Add(this.tbMothername, 0, 1);
            this.tableLayoutPanel2.Controls.Add(this.tbAddress, 1, 2);
            this.tableLayoutPanel2.Location = new System.Drawing.Point(18, 143);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 3;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(670, 282);
            this.tableLayoutPanel2.TabIndex = 10;
            // 
            // tbFatheroccupation
            // 
            this.tbFatheroccupation.AcceptsReturn = false;
            this.tbFatheroccupation.AcceptsTab = false;
            this.tbFatheroccupation.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbFatheroccupation.AnimationSpeed = 200;
            this.tbFatheroccupation.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbFatheroccupation.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbFatheroccupation.BackColor = System.Drawing.Color.Transparent;
            this.tbFatheroccupation.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbFatheroccupation.BackgroundImage")));
            this.tbFatheroccupation.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbFatheroccupation.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbFatheroccupation.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbFatheroccupation.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbFatheroccupation.BorderRadius = 10;
            this.tbFatheroccupation.BorderThickness = 2;
            this.tbFatheroccupation.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbFatheroccupation.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFatheroccupation.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbFatheroccupation.DefaultText = "";
            this.tbFatheroccupation.FillColor = System.Drawing.Color.White;
            this.tbFatheroccupation.HideSelection = true;
            this.tbFatheroccupation.IconLeft = null;
            this.tbFatheroccupation.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFatheroccupation.IconPadding = 10;
            this.tbFatheroccupation.IconRight = null;
            this.tbFatheroccupation.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFatheroccupation.Lines = new string[0];
            this.tbFatheroccupation.Location = new System.Drawing.Point(398, 28);
            this.tbFatheroccupation.MaxLength = 32767;
            this.tbFatheroccupation.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbFatheroccupation.Modified = false;
            this.tbFatheroccupation.Multiline = false;
            this.tbFatheroccupation.Name = "tbFatheroccupation";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFatheroccupation.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbFatheroccupation.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFatheroccupation.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFatheroccupation.OnIdleState = stateProperties20;
            this.tbFatheroccupation.Padding = new System.Windows.Forms.Padding(3);
            this.tbFatheroccupation.PasswordChar = '\0';
            this.tbFatheroccupation.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbFatheroccupation.PlaceholderText = "Father Occupation";
            this.tbFatheroccupation.ReadOnly = false;
            this.tbFatheroccupation.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbFatheroccupation.SelectedText = "";
            this.tbFatheroccupation.SelectionLength = 0;
            this.tbFatheroccupation.SelectionStart = 0;
            this.tbFatheroccupation.ShortcutsEnabled = true;
            this.tbFatheroccupation.Size = new System.Drawing.Size(208, 37);
            this.tbFatheroccupation.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbFatheroccupation.TabIndex = 3;
            this.tbFatheroccupation.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbFatheroccupation.TextMarginBottom = 0;
            this.tbFatheroccupation.TextMarginLeft = 3;
            this.tbFatheroccupation.TextMarginTop = 0;
            this.tbFatheroccupation.TextPlaceholder = "Father Occupation";
            this.tbFatheroccupation.UseSystemPasswordChar = false;
            this.tbFatheroccupation.WordWrap = true;
            // 
            // tbFathername
            // 
            this.tbFathername.AcceptsReturn = false;
            this.tbFathername.AcceptsTab = false;
            this.tbFathername.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbFathername.AnimationSpeed = 200;
            this.tbFathername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbFathername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbFathername.BackColor = System.Drawing.Color.Transparent;
            this.tbFathername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbFathername.BackgroundImage")));
            this.tbFathername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbFathername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbFathername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbFathername.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbFathername.BorderRadius = 10;
            this.tbFathername.BorderThickness = 2;
            this.tbFathername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbFathername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFathername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbFathername.DefaultText = "";
            this.tbFathername.FillColor = System.Drawing.Color.White;
            this.tbFathername.HideSelection = true;
            this.tbFathername.IconLeft = null;
            this.tbFathername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFathername.IconPadding = 10;
            this.tbFathername.IconRight = null;
            this.tbFathername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFathername.Lines = new string[0];
            this.tbFathername.Location = new System.Drawing.Point(63, 28);
            this.tbFathername.MaxLength = 32767;
            this.tbFathername.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbFathername.Modified = false;
            this.tbFathername.Multiline = false;
            this.tbFathername.Name = "tbFathername";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFathername.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbFathername.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFathername.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFathername.OnIdleState = stateProperties24;
            this.tbFathername.Padding = new System.Windows.Forms.Padding(3);
            this.tbFathername.PasswordChar = '\0';
            this.tbFathername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbFathername.PlaceholderText = "Father Name";
            this.tbFathername.ReadOnly = false;
            this.tbFathername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbFathername.SelectedText = "";
            this.tbFathername.SelectionLength = 0;
            this.tbFathername.SelectionStart = 0;
            this.tbFathername.ShortcutsEnabled = true;
            this.tbFathername.Size = new System.Drawing.Size(208, 37);
            this.tbFathername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbFathername.TabIndex = 3;
            this.tbFathername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbFathername.TextMarginBottom = 0;
            this.tbFathername.TextMarginLeft = 3;
            this.tbFathername.TextMarginTop = 0;
            this.tbFathername.TextPlaceholder = "Father Name";
            this.tbFathername.UseSystemPasswordChar = false;
            this.tbFathername.WordWrap = true;
            // 
            // tbMotheroccupation
            // 
            this.tbMotheroccupation.AcceptsReturn = false;
            this.tbMotheroccupation.AcceptsTab = false;
            this.tbMotheroccupation.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbMotheroccupation.AnimationSpeed = 200;
            this.tbMotheroccupation.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbMotheroccupation.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbMotheroccupation.BackColor = System.Drawing.Color.Transparent;
            this.tbMotheroccupation.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbMotheroccupation.BackgroundImage")));
            this.tbMotheroccupation.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbMotheroccupation.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbMotheroccupation.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbMotheroccupation.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbMotheroccupation.BorderRadius = 10;
            this.tbMotheroccupation.BorderThickness = 2;
            this.tbMotheroccupation.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbMotheroccupation.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMotheroccupation.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbMotheroccupation.DefaultText = "";
            this.tbMotheroccupation.FillColor = System.Drawing.Color.White;
            this.tbMotheroccupation.HideSelection = true;
            this.tbMotheroccupation.IconLeft = null;
            this.tbMotheroccupation.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMotheroccupation.IconPadding = 10;
            this.tbMotheroccupation.IconRight = null;
            this.tbMotheroccupation.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMotheroccupation.Lines = new string[0];
            this.tbMotheroccupation.Location = new System.Drawing.Point(398, 122);
            this.tbMotheroccupation.MaxLength = 32767;
            this.tbMotheroccupation.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbMotheroccupation.Modified = false;
            this.tbMotheroccupation.Multiline = false;
            this.tbMotheroccupation.Name = "tbMotheroccupation";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMotheroccupation.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbMotheroccupation.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMotheroccupation.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMotheroccupation.OnIdleState = stateProperties28;
            this.tbMotheroccupation.Padding = new System.Windows.Forms.Padding(3);
            this.tbMotheroccupation.PasswordChar = '\0';
            this.tbMotheroccupation.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbMotheroccupation.PlaceholderText = "Mother Occupation";
            this.tbMotheroccupation.ReadOnly = false;
            this.tbMotheroccupation.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbMotheroccupation.SelectedText = "";
            this.tbMotheroccupation.SelectionLength = 0;
            this.tbMotheroccupation.SelectionStart = 0;
            this.tbMotheroccupation.ShortcutsEnabled = true;
            this.tbMotheroccupation.Size = new System.Drawing.Size(208, 37);
            this.tbMotheroccupation.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbMotheroccupation.TabIndex = 3;
            this.tbMotheroccupation.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbMotheroccupation.TextMarginBottom = 0;
            this.tbMotheroccupation.TextMarginLeft = 3;
            this.tbMotheroccupation.TextMarginTop = 0;
            this.tbMotheroccupation.TextPlaceholder = "Mother Occupation";
            this.tbMotheroccupation.UseSystemPasswordChar = false;
            this.tbMotheroccupation.WordWrap = true;
            // 
            // tbParentcontact
            // 
            this.tbParentcontact.AcceptsReturn = false;
            this.tbParentcontact.AcceptsTab = false;
            this.tbParentcontact.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbParentcontact.AnimationSpeed = 200;
            this.tbParentcontact.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbParentcontact.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbParentcontact.BackColor = System.Drawing.Color.Transparent;
            this.tbParentcontact.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbParentcontact.BackgroundImage")));
            this.tbParentcontact.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbParentcontact.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbParentcontact.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbParentcontact.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbParentcontact.BorderRadius = 10;
            this.tbParentcontact.BorderThickness = 2;
            this.tbParentcontact.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbParentcontact.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbParentcontact.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbParentcontact.DefaultText = "";
            this.tbParentcontact.FillColor = System.Drawing.Color.White;
            this.tbParentcontact.HideSelection = true;
            this.tbParentcontact.IconLeft = null;
            this.tbParentcontact.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbParentcontact.IconPadding = 10;
            this.tbParentcontact.IconRight = null;
            this.tbParentcontact.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbParentcontact.Lines = new string[0];
            this.tbParentcontact.Location = new System.Drawing.Point(63, 216);
            this.tbParentcontact.MaxLength = 32767;
            this.tbParentcontact.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbParentcontact.Modified = false;
            this.tbParentcontact.Multiline = false;
            this.tbParentcontact.Name = "tbParentcontact";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbParentcontact.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbParentcontact.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbParentcontact.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbParentcontact.OnIdleState = stateProperties32;
            this.tbParentcontact.Padding = new System.Windows.Forms.Padding(3);
            this.tbParentcontact.PasswordChar = '\0';
            this.tbParentcontact.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbParentcontact.PlaceholderText = "Parent Contact";
            this.tbParentcontact.ReadOnly = false;
            this.tbParentcontact.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbParentcontact.SelectedText = "";
            this.tbParentcontact.SelectionLength = 0;
            this.tbParentcontact.SelectionStart = 0;
            this.tbParentcontact.ShortcutsEnabled = true;
            this.tbParentcontact.Size = new System.Drawing.Size(208, 37);
            this.tbParentcontact.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbParentcontact.TabIndex = 3;
            this.tbParentcontact.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbParentcontact.TextMarginBottom = 0;
            this.tbParentcontact.TextMarginLeft = 3;
            this.tbParentcontact.TextMarginTop = 0;
            this.tbParentcontact.TextPlaceholder = "Parent Contact";
            this.tbParentcontact.UseSystemPasswordChar = false;
            this.tbParentcontact.WordWrap = true;
            // 
            // tbMothername
            // 
            this.tbMothername.AcceptsReturn = false;
            this.tbMothername.AcceptsTab = false;
            this.tbMothername.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbMothername.AnimationSpeed = 200;
            this.tbMothername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbMothername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbMothername.BackColor = System.Drawing.Color.Transparent;
            this.tbMothername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbMothername.BackgroundImage")));
            this.tbMothername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbMothername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbMothername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbMothername.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbMothername.BorderRadius = 10;
            this.tbMothername.BorderThickness = 2;
            this.tbMothername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbMothername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMothername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbMothername.DefaultText = "";
            this.tbMothername.FillColor = System.Drawing.Color.White;
            this.tbMothername.HideSelection = true;
            this.tbMothername.IconLeft = null;
            this.tbMothername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMothername.IconPadding = 10;
            this.tbMothername.IconRight = null;
            this.tbMothername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMothername.Lines = new string[0];
            this.tbMothername.Location = new System.Drawing.Point(63, 122);
            this.tbMothername.MaxLength = 32767;
            this.tbMothername.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbMothername.Modified = false;
            this.tbMothername.Multiline = false;
            this.tbMothername.Name = "tbMothername";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMothername.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbMothername.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMothername.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMothername.OnIdleState = stateProperties36;
            this.tbMothername.Padding = new System.Windows.Forms.Padding(3);
            this.tbMothername.PasswordChar = '\0';
            this.tbMothername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbMothername.PlaceholderText = "Mother Name";
            this.tbMothername.ReadOnly = false;
            this.tbMothername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbMothername.SelectedText = "";
            this.tbMothername.SelectionLength = 0;
            this.tbMothername.SelectionStart = 0;
            this.tbMothername.ShortcutsEnabled = true;
            this.tbMothername.Size = new System.Drawing.Size(208, 37);
            this.tbMothername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbMothername.TabIndex = 3;
            this.tbMothername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbMothername.TextMarginBottom = 0;
            this.tbMothername.TextMarginLeft = 3;
            this.tbMothername.TextMarginTop = 0;
            this.tbMothername.TextPlaceholder = "Mother Name";
            this.tbMothername.UseSystemPasswordChar = false;
            this.tbMothername.WordWrap = true;
            // 
            // tbAddress
            // 
            this.tbAddress.AcceptsReturn = false;
            this.tbAddress.AcceptsTab = false;
            this.tbAddress.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbAddress.AnimationSpeed = 200;
            this.tbAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbAddress.BackColor = System.Drawing.Color.Transparent;
            this.tbAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbAddress.BackgroundImage")));
            this.tbAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbAddress.BorderRadius = 10;
            this.tbAddress.BorderThickness = 2;
            this.tbAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbAddress.DefaultText = "";
            this.tbAddress.FillColor = System.Drawing.Color.White;
            this.tbAddress.HideSelection = true;
            this.tbAddress.IconLeft = null;
            this.tbAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.IconPadding = 10;
            this.tbAddress.IconRight = null;
            this.tbAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.Lines = new string[0];
            this.tbAddress.Location = new System.Drawing.Point(345, 216);
            this.tbAddress.MaxLength = 32767;
            this.tbAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbAddress.Modified = false;
            this.tbAddress.Multiline = false;
            this.tbAddress.Name = "tbAddress";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbAddress.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnIdleState = stateProperties40;
            this.tbAddress.Padding = new System.Windows.Forms.Padding(3);
            this.tbAddress.PasswordChar = '\0';
            this.tbAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbAddress.PlaceholderText = "Address";
            this.tbAddress.ReadOnly = false;
            this.tbAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbAddress.SelectedText = "";
            this.tbAddress.SelectionLength = 0;
            this.tbAddress.SelectionStart = 0;
            this.tbAddress.ShortcutsEnabled = true;
            this.tbAddress.Size = new System.Drawing.Size(315, 37);
            this.tbAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbAddress.TabIndex = 3;
            this.tbAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tbAddress.TextMarginBottom = 0;
            this.tbAddress.TextMarginLeft = 3;
            this.tbAddress.TextMarginTop = 0;
            this.tbAddress.TextPlaceholder = "Address";
            this.tbAddress.UseSystemPasswordChar = false;
            this.tbAddress.WordWrap = true;
            // 
            // btnCancelFamilyTab
            // 
            this.btnCancelFamilyTab.Animated = true;
            this.btnCancelFamilyTab.AnimatedGIF = true;
            this.btnCancelFamilyTab.BackColor = System.Drawing.Color.Transparent;
            this.btnCancelFamilyTab.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btnCancelFamilyTab.BorderRadius = 12;
            this.btnCancelFamilyTab.BorderThickness = 1;
            this.btnCancelFamilyTab.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnCancelFamilyTab.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnCancelFamilyTab.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnCancelFamilyTab.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnCancelFamilyTab.FillColor = System.Drawing.Color.Transparent;
            this.btnCancelFamilyTab.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnCancelFamilyTab.ForeColor = System.Drawing.Color.Black;
            this.btnCancelFamilyTab.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(190)))), ((int)(((byte)(51)))), ((int)(((byte)(0)))));
            this.btnCancelFamilyTab.HoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(190)))), ((int)(((byte)(51)))), ((int)(((byte)(0)))));
            this.btnCancelFamilyTab.HoverState.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.cancel__1_;
            this.btnCancelFamilyTab.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.cancel;
            this.btnCancelFamilyTab.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.btnCancelFamilyTab.Location = new System.Drawing.Point(6, 454);
            this.btnCancelFamilyTab.Name = "btnCancelFamilyTab";
            this.btnCancelFamilyTab.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(190)))), ((int)(((byte)(51)))), ((int)(((byte)(0)))));
            this.btnCancelFamilyTab.Size = new System.Drawing.Size(110, 39);
            this.btnCancelFamilyTab.TabIndex = 7;
            this.btnCancelFamilyTab.Text = "Cancel";
            this.btnCancelFamilyTab.UseTransparentBackground = true;
            this.btnCancelFamilyTab.Click += new System.EventHandler(this.btnCancelFamilyTab_Click);
            // 
            // btnInsert
            // 
            this.btnInsert.Animated = true;
            this.btnInsert.AnimatedGIF = true;
            this.btnInsert.BackColor = System.Drawing.Color.Transparent;
            this.btnInsert.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btnInsert.BorderRadius = 12;
            this.btnInsert.BorderThickness = 1;
            this.btnInsert.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnInsert.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnInsert.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnInsert.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnInsert.FillColor = System.Drawing.Color.Transparent;
            this.btnInsert.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnInsert.ForeColor = System.Drawing.Color.Black;
            this.btnInsert.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(214)))), ((int)(((byte)(80)))));
            this.btnInsert.HoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(111)))), ((int)(((byte)(41)))));
            this.btnInsert.HoverState.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.add__1_;
            this.btnInsert.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.add;
            this.btnInsert.ImageAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.btnInsert.Location = new System.Drawing.Point(592, 456);
            this.btnInsert.Name = "btnInsert";
            this.btnInsert.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(239)))), ((int)(((byte)(209)))));
            this.btnInsert.Size = new System.Drawing.Size(110, 39);
            this.btnInsert.TabIndex = 6;
            this.btnInsert.Text = "Add";
            this.btnInsert.UseTransparentBackground = true;
            this.btnInsert.Click += new System.EventHandler(this.btnInsert_Click);
            // 
            // btnBack
            // 
            this.btnBack.Animated = true;
            this.btnBack.AnimatedGIF = true;
            this.btnBack.BackColor = System.Drawing.Color.Transparent;
            this.btnBack.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btnBack.BorderRadius = 12;
            this.btnBack.BorderThickness = 1;
            this.btnBack.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnBack.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnBack.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnBack.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnBack.FillColor = System.Drawing.Color.Transparent;
            this.btnBack.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnBack.ForeColor = System.Drawing.Color.Black;
            this.btnBack.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(7)))), ((int)(((byte)(7)))));
            this.btnBack.HoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(96)))), ((int)(((byte)(164)))));
            this.btnBack.HoverState.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.left_arrow_in_circular_button_black_symbol__1_;
            this.btnBack.Image = global::OraclaMajorAssignmentY3S2.Properties.Resources.left_arrow_in_circular_button_black_symbol;
            this.btnBack.ImageAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.btnBack.Location = new System.Drawing.Point(3, 3);
            this.btnBack.Name = "btnBack";
            this.btnBack.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(5)))), ((int)(((byte)(5)))));
            this.btnBack.Size = new System.Drawing.Size(40, 39);
            this.btnBack.TabIndex = 5;
            this.btnBack.UseTransparentBackground = true;
            this.btnBack.Click += new System.EventHandler(this.btnBack_Click);
            // 
            // guna2Panel1
            // 
            this.guna2Panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(42)))), ((int)(((byte)(57)))));
            this.guna2Panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.guna2Panel1.Location = new System.Drawing.Point(0, 0);
            this.guna2Panel1.Name = "guna2Panel1";
            this.guna2Panel1.Size = new System.Drawing.Size(719, 25);
            this.guna2Panel1.TabIndex = 1;
            // 
            // guna2DragControl1
            // 
            this.guna2DragControl1.DockIndicatorTransparencyValue = 0.6D;
            this.guna2DragControl1.TargetControl = this.guna2Panel1;
            this.guna2DragControl1.UseTransparentDrag = true;
            // 
            // InputForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(719, 527);
            this.Controls.Add(this.guna2Panel1);
            this.Controls.Add(this.InputTabControll);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ImeMode = System.Windows.Forms.ImeMode.Off;
            this.Name = "InputForm";
            this.Text = "zz";
            this.InputTabControll.ResumeLayout(false);
            this.StudentTab.ResumeLayout(false);
            this.StudentTab.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.guna2PictureBox1)).EndInit();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.familyTab.ResumeLayout(false);
            this.familyTab.PerformLayout();
            this.tableLayoutPanel2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private Guna.UI2.WinForms.Guna2TabControl InputTabControll;
        private System.Windows.Forms.TabPage StudentTab;
        private System.Windows.Forms.TabPage familyTab;
        private Guna.UI2.WinForms.Guna2Button btnNext;
        private Guna.UI2.WinForms.Guna2Button btnBack;
        private Guna.UI2.WinForms.Guna2Panel guna2Panel1;
        private Guna.UI2.WinForms.Guna2DragControl guna2DragControl1;
        private Guna.UI2.WinForms.Guna2Button btnInsert;
        private Guna.UI2.WinForms.Guna2Button btnCancelFamilyTab;
        private Guna.UI2.WinForms.Guna2Button btnCancelStudentTab;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox tbLastname;
        private Bunifu.UI.WinForms.BunifuTextBox tbFirstname;
        private Bunifu.UI.WinForms.BunifuTextBox tbContact;
        private Bunifu.UI.WinForms.BunifuTextBox tbEmail;
        private Guna.UI2.WinForms.Guna2ComboBox cbGender;
        private Guna.UI2.WinForms.Guna2DateTimePicker dtpDob;
        private Guna.UI2.WinForms.Guna2Button btnTakePhoto;
        private Guna.UI2.WinForms.Guna2Button btnFromfile;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private Bunifu.UI.WinForms.BunifuTextBox tbFatheroccupation;
        private Bunifu.UI.WinForms.BunifuTextBox tbFathername;
        private Bunifu.UI.WinForms.BunifuTextBox tbMotheroccupation;
        private Bunifu.UI.WinForms.BunifuTextBox tbParentcontact;
        private Bunifu.UI.WinForms.BunifuTextBox tbMothername;
        private Bunifu.UI.WinForms.BunifuTextBox tbAddress;
        private Guna.UI2.WinForms.Guna2PictureBox guna2PictureBox1;
    }
}